export const styles = {
  container: { width: { xs: "auto", md: "98%" }, mx: "auto", mt: "0.5rem" },
  tabsContainer: {
    minWidth: "300px",
    overflowX: "auto",
    overflowY: "hidden",
    whiteSpace: "nowrap",
    color: "#E36419",
    fontWeight: 600,
    height: "60px",
    mb: "1rem",
  },
  tab: {
    textWrap: "nowrap",
    textTransform: "capitalize",
    height: "50px",
    display: "inline-block",
    p: 0,
    m: 0,
    color: "inherit",
    fontWeight: "inherit",
    textAlign: "start",
    mx: "1rem",
    borderRadius: 0,
    position: "relative",
  },
  tabsAfter: {
    content: "''",
    display: "block",
    width: "30%",
    height: "3px",
    position: "absolute",
    bottom: 0,
    left: 0,
  },
};
